dataset:
  channels_num: &channels_num 3
  image_size: &image_size 224 # CIFAR-100 image size
  num_classes: &num_clases 100 # CIFAR-100 number of classes
model:
  # values here are described in the Vit.__init__ method
  # Pairing some params from 'dataset' to 'vit' to avoid duplication
  channels_num: *channels_num
  image_size: *image_size
  num_classes: *num_clases
  
  pool: 'cls'
  embed_depth: 768 # 'hidden_size' in LGViT
  patch_size: 16 
  num_attn_heads: 12 # 'num_attention_heads' in LGViT
  dropout_embedding: 0.0 
  dropout_transformer: 0.0 
  mlp_dim: 3072 # 'intermediate_size' in LGVIT
  dim_head: 64 # computed as config.hidden_size / config.num_attention_heads in LGVIT
  num_layers_transformer: 12 # 'num_hidden_layers' in LGViT