dataset:
  channels_num: &channels_num 3
  image_size: &image_size 256 # TODO: Change to CIFAR-100 image size
  num_classes: &num_clases 10 # TODO: Change to meet LGViT details
model:
  # values here are described in the Vit.__init__ method
  # Pairing some params from 'dataset' to 'vit' to avoid duplication
  channels_num: *channels_num
  image_size: *image_size
  num_classes: *num_clases
  
  pool: 'cls'
  embed_depth: 1024

  # TODO: Change these to meet LGViT details
  dropout_embedding: 0.0 
  dropout_transformer: 0.0 
  dim_head: 64 
  num_attn_heads: 16 
  mlp_dim: 204 
  patch_size: 32 
  num_layers_transformer: 2